source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'GroupManagement' do
    # use_frameworks!
    pod 'MASFoundation', '~> 1.6.00'
    pod 'MASUI', '~> 1.6.00'
    pod 'MASIdentityManagement', '~> 1.6.00'
    
end
